### ISSUE TITLE
Supported platforms?

### ISSUE THREAD

**Issue by neuromancer** [r1sc/Open76#5]
Hi, 

I wonder which are the platforms you plan to support for Open76. It will be nice to have a Linux version of it.

**Comment by r1sc** [comment]
Since it runs under the Unity Engine, having a Linux version would be no issue. Here's a list of the platforms Unity currently supports: https://unity3d.com/unity/features/multiplatform

**Comment by neuromancer** [comment]
> Since it runs under the Unity Engine, having a Linux version would be no issue.

Great!, so if you want some testers for the linux builds, let me know.
